db:
  name: oracle
  password: pass
  pool.size: 12
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1

spring.profiles.active: web
logging:
  level:
    root: info
    org.springframework: info
    org.hibernate: info
#  file:
#    name: log/test.log
#    path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/spring-demo
    username: admin
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl.auto: validate
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
#        default_batch_fetch_size: 50
